config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
  resources :users
  root 'welcome#index'

  get '/help/' => 'static_pages#help'
  get '/about/' => 'static_pages#about'
  get '/login/' => 'sessions#new'
  post '/login/' => 'sessions#create'
  delete '/logout/' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord


  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  protected
    def authenticate_user!
      if logged_in?
        
      else
        redirect_to '/login/'
      end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :except => [:index,:show]
  def index
    @articles = Article.all
    
    @cutter = CutLen.new()
    @articles = @cutter.cut(@articles)
  end
  
  def new 
  end

  def create
    @article = Article.new(article_params)
    #@article[:email]
    @article.save 

    redirect_to @article
  end

  def show 
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
        redirect_to @article
    else
       render 'edit'
    end
  end

  def destroy
   @article = Article.find(params[:id])
   @article.destroy 

   redirect_to '/articles/'
  end

  private
    def article_params
      params.require(:article).permit(:title,:text)
    end
end

app/controllers/articles_controller/cut_len.rb
class ArticlesController
  
  class CutLen
    def cut(articles)
      for article in articles
        if article[:text].length > 500
          article[:text] = article[:text][0..500] +  "..."
        else

        end  
      end
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      puts "LOGIN SUCCESFUL"
      log_in user

      redirect_to root_url
    else
      render 'new'
    end


  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  protect_from_forgery with: :exception

  def about
  end

  def help
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!  
  def new
  end

  def create
    @user = User.new(user_params)
    @user.save

    redirect_to @user
  end

  def show
    @user = User.find(params[:id])
  end

  private 
    def user_params
      params.require(:user).permit(:username,:email,:password, :password_confirmation, :current_password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  protect_from_forgery with: :exception

  def index
    @article = Article.last
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

end

app/views/articles/edit.html.erb
<% provide(:title,"Edit Post")%>
<div class="new-post">
  <h1>Edit Article</h1>
  <strong> This file lives in app/views/articles/edit.html.erb/ </strong>
  <br>
  <br>
<%= form_for(@article) do |f| %>
  <p>
    <%= f.label :title %>
    <br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :title %>
    <br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit "Save Changes"%>
  </p>
<% end %>
</div>

app/views/articles/index.html.erb
<% provide(:title,"Articles")%>

<div class="jumbotron">
  <h1>Articles</h1>
  <strong> This file lives in /app/views/articles/index.html.erb/</strong>
</div>


<% @articles.reverse.each do |article|%>
  <div class='article-box'>

    
    <div class="post-content">
      <strong><h3><%= article[:title]%></h3></strong>
      <h5><%= article[:created_at].localtime.strftime("%Y-%m-%d")%> </h5>
      <br>
      <%= article[:text]%>
    </div>

    <br>

    <%= link_to "View Full Post", '/articles/'+ article[:id].to_s, :class => "action-buttons"%> 
  </div>

  <br>
  <br>

<%end%>

app/views/articles/new.html.erb
<% provide(:title,"New Post")%>
<div class='new-post'>

  <h1> New Article </h1>
  <strong> This file lives in app/views/articles/new.html.erb/ </strong>
  <br>
  <br>
    <%= form_for :article, url: articles_path do |f| %>
        
        <p>
          <%= f.label :title %><br>
          <%= f.text_field :title %>
        </p>

        <p>
          <%= f.label :text %><br>

          <div class='content-text'>
            <%= f.text_area :text %>
          </div>
        </p>

        <%= f.submit :class => "action-buttons" %>

      <% end%>

</div>

app/views/articles/show.html.erb
<% provide(:title, "Show Post")%>
<strong> This file lives in app/views/articles/show.html.erb </strong>
<p>
  <strong><h3><%= @article.title%> </strong></h3>
</p>

<h5> <%= @article.created_at.localtime.strftime("%Y-%m-%d") %> </h5>


<%= @article.text%>
<br>
<br>
<% if logged_in? %>
  <%= link_to "Edit", @article.id.to_s + "/edit/", :class => "action-buttons"%> <%= link_to "Delete", '', method: :delete, data: { confirm: 'Are you sure?'}, :class => "action-buttons" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <title><%= "Small Blog | " + yield(:title)%></title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <nav class="the-nav nav navbar-default navbar-fixed-top">
      <div class="container">


      
        <div class="navbar-header">
          <strong class="navbar-brand"> <%= link_to "Small Blog","/"%></strong>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-items" >
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
         
          </button>
        </div>




          <div class="collapse navbar-collapse" id="header-items">

          <ul class="nav navbar-nav navbar">

            <li class="nav-item">
              <%= link_to "About", "/about/"%>
            </li>

            <li class="nav-item">
              <%= link_to "Articles", "/articles/" %>
            </li>
 
            <li class="nav-item">
              <%= link_to "Help", "/help/"%>
            </li>
        
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>

            <li class="nav-item">
              <%= link_to "Create User", "/users/new" %>
            </li>
           
            <li class="nav-item">
              <%= link_to "Create Post", "/articles/new/"%>
            </li>
            
            <li class="nav-item">
              <%= link_to "Log Out", "/logout/", method: :delete %>
            </li>

            <% else %>
              <li class="nav-item">
                <%= link_to "Log In", "/login/" %>
              </li>
            <% end %>
          </ul>

         </div>


      </div> 
    </nav>

    </div>


      <div class="container site-content"> 
        <%= yield %> 
      </div>
  </body>

</html>

app/views/static_pages/about.html.erb
<% provide(:title,"About")%>
<div class="jumbotron">
  <h1> About </h1>
  <strong> This file lives in /app/views/static_pages/about.html.erb/ </strong>
  <br>
  <br>
  <p>This is a sample blog solely created for learning RoR, in no way is it unique but implements the standards of backend development coupled with basic frontned design using Bootstrap.</p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title,"Help")%>
<div class="jumbotron">
  <h1> Help </h1>
  <strong> This file lives in /app/views/static_pages/help.html.erb/ </strong>
  <br>
  <br>
  <p> This project's repo can be accessed at https://github.com/jcgalbano/rails-small-blog </p
</div>

app/views/users/index.html.erb
<h1> Login </h1>

app/views/users/new.html.erb
<% provide(:title,"Create User") %>
<div class="new-post">
    <h1> Create User </h1>
    <strong> This file lives in app/views/users/new.html.erb/ </strong>
    <br>
    <br>
    <%= form_for :user, url: users_path do |f| %>

      <p>
      <%= f.label :username %>
      <br>
      <%= f.text_field :username %>
      </p>
      <p>
      <%= f.label :email%>
      <br>
      <%= f.text_field :email %>
      </p>
      
      <p>
      <%= f.label :password %>
      <br>
      <%= f.password_field :password %>
      </p>
      <%= f.submit :class => "action-buttons" %>

    <% end %>

</div>

app/views/users/show.html.erb
<h2> Succesfully Created User </h1>

<br>
<h4> Username </h4>
<%= @user.username %>
<br>

<h4> Email </h4>
<%= @user.email%>

app/views/welcome/index.html.erb
<% provide(:title,"Home")%>
<div class="jumbotron">
  <h1> Welcome to the Home Page </h1>
  <strong> This file lives in /app/views/welcome/index.html.erb/</strong>
</div>
  <div class='article-box'>

    
    <div class="post-content">
      <div id="latest-label">
        <h2>Latest Entry</h2>
      </div>
      <strong><h3><%= @article[:title]%></h3></strong>
      <h5><%= @article[:created_at].localtime.strftime("%Y-%m-%d")%> </h5>
      <br>
      <%= @article[:text]%>
    </div>

    <br>

  </div>